Feature/gui-input-expression-style
Mala1180/PPS-22-satify pull request #106
Opened 2023-09-15 16:40 UTC by w-disaster

- Substitute `TextArea` with `TextPane`
- Styled operators inside input `TextPane`

2023-09-17 08:30 UTC, Mala1180 commented on src/main/scala/satify/view/ComponentUtils.scala
> +    val tf = new TextField:
Why did you insert val?

2023-09-17 08:33 UTC, Mala1180 requested changes

2023-09-17 08:33 UTC, Mala1180 commented on src/main/scala/satify/view/ComponentUtils.scala
> +      def g(l: List[Int], length: Int): Unit = Swing.onEDT {
I would change names of `f` `g` and `h`

2023-09-17 08:35 UTC, w-disaster commented on src/main/scala/satify/view/ComponentUtils.scala
> +    val tf = new TextField:
That's a typo, thanks for reporting it

2023-09-17 08:37 UTC, w-disaster commented on src/main/scala/satify/view/ComponentUtils.scala
> +      def g(l: List[Int], length: Int): Unit = Swing.onEDT {
Alright!

2023-09-18 10:06 UTC, Mala1180 approved these changes

2023-09-18 10:07 UTC, merged